### ISSUE TITLE
why is the export to assimp option disabled?

### ISSUE THREAD

**Issue by D3fa1t1** [gregkwaste/NMSMV#1]
![image](https://user-images.githubusercontent.com/77608590/150988473-16b320a6-22f3-482f-939d-2fddab06d297.png)
right click > export to assimp

**Comment by gregkwaste** [comment]
its a work in progress :D. Couldn't interface properly with the assimp library in the old version of the code. The engine version in the develop branch will support an Assimp Plugin that will allow for all sorts of model exports using Assimp. Unfortunately I don't have an ETA for that though :(

**Comment by gregkwaste** [comment]
That is my goal yes! Convert everything to the assimp internal format and then be able to export assets into any format, fbx, gltf, whatever assimp supports!

**Comment by D3fa1t1** [comment]
I will wish you luck as i cant really program myself!

**Comment by D3fa1t1** [comment]
its been 7/8th of a year now, do you have any updates on this topic?

**Comment by gregkwaste** [comment]
> its been 7/8th of a year now, do you have any updates on this topic?

I'm still working on this (my time was very limited pretty much the entire year), I've actually done a ton of progress regarding export to assimp in Nibble. In fact, last week I added export support for skinned meshes and the only thing that remains to be exported are animations.

However there are issues that I'm not capable of fixing right now. It seems either AssimpNET or the assimp library are not capable of exporting all material properties and this is what I was working on as well. The new engine adopts a PBR pipeline for all objects for now so its kinda essential to include related uniforms and samplers on the exported object. Also I'm really not sure what else is gonna come up using Assimp, at this point I'm crossing fingers regarding animations as well. The import process for both PBR stuff and Animations seems to be working perfectly, hopefully export won't hide any more surprises regarding these aspects.


With regards to NMSMV, given that the AssimpPlugin that I'm working on has already a lot of work I think its gonna be a waste of time to try to make it backwards compatible (it aint that easy, the engine has got a substantial rewriting). However, one of the first things that I did for the new engine using that plugin system was to move and adapt the entire NMS asset (which since the release of the game are intended for PBR) import procedure  to a separate plugin for the Nibble Engine. This means that as soon as I get both plugins up and running you will be able to use the Nibble Editor (the frontend of Nibble) to import NMS assets as well as any other assimp supported asset and also to export your current scene using assimp to the format of your choice.

TL,DR: Assimp import/export will be supported in Nibble (an upgraded and more abstracted version of the NMSMV) and probably won't be included in any future version of the NMSMV.
