### ISSUE TITLE
Texture Export 

### ISSUE THREAD

**Issue by TheLifeweaver** [gregkwaste/NMSMV#7]
Not sure if this is even in scope but would you consider adding texture exporting?

**Comment by gregkwaste** [comment]
Hi @TheLifeweaver, not for the time being. The problem is, that the viewer does not use the vanilla textures. The vanilla textures are meant to be combined to get a final texture for the  models and it would be meaningless to export these textures imho.

If you need the vanilla textures, you can unpack the game files and grab them from there.

If you are thinking of something different let me know.

**Comment by TheLifeweaver** [comment]
Ah fair - my logic behind asking was to allow for quicker material setup by providing the textures and a .txt. output that roughly outlines how the software is generating the final texture. I believe UModel does something similar to this. Again I totally understand where you're coming from and also understand that it might not be worth the hassle.

**Comment by gregkwaste** [comment]
> Ah fair - my logic behind asking was to allow for quicker material setup by providing the textures and a .txt. output that roughly outlines how the software is generating the final texture. I believe UModel does something similar to this. Again I totally understand where you're coming from and also understand that it might not be worth the hassle.

Well, in this case, there should be quite some info about the loaded and selected textures on the log file. Take a look there and you'll find the selected textures using in the recombination process. I'll take another look and see if I can make the log a bit clearer.
